from math import pi, tan

SCREEN_SIZE = (1200, 450)
FRAMERATE = 60
SCALE = 50

START_POS = (1, 1)
ROTATION_SPEED = 0.02
MOVEMENT_SPEED = 2

FOV = pi / 3
RAYS_NUMBER = SCREEN_SIZE[0] // 2
RAY_WIDTH = SCREEN_SIZE[0] // RAYS_NUMBER
DELTA_ANGLE = FOV / RAYS_NUMBER
SCREEN_DISTANCE = SCREEN_SIZE[0] // 2 / tan(FOV / 2)

LIGHT = 2

NULL = 0.0001
